language: node_js
node_js:
- '6'

env:
  global:
    secure: eKnf6QZyQvilqid1j3/2o69waBpe6ixBErVhkXtWAnLGTFwg6XFORjIqtIGucCt6KPV/7E+pLUMKRWMmCfNGbX0GUDj4SFknpxK+/LsgnSdgOEY2lG0K092ApMW9wzpW/OellArCjQYc8PEKamGdzE98QuSTMVzcnLWOFz4a83KLa4fDXzF1RCCXoQtZvM1gDCP307QuRLEFUvRIoRrY9cKov8s4W9yKESi67WILzN+K7dF6KI3IR7YtVCGk4dThfHjxjFnOFiuL0y6Z2xiUWYcfv8nLP60VOtuygzCCNuoaahFmJYDsb0mOEO5kH4zvMZJdeiVYDBiy403ayMggDafAOWFiSal7C4XEsFmeUqDXTsA6ZVsGYxcxC3oOAB1bXc4Dzmb4802TeyvUSY13pea5F/l+N1IbDUrQqMLj3FSZLu9PmLWnodQ6i5MhSxEMLd56UHFB2T9HsHs8rljxzCDK7+8NUZFEvFIk/cixcTPPAGp6yJGdoSXj4wOEn4r7iUuhZKzUl0GekPG1mbNUw6eZQVXdhyc3mRsQkIKbPm2wYfblS8BlEGT9rd7bUUQqJotExbyzOg54vhiB0NVG9oH4N9Qq0mvOBLfmrEh/FWzFSqDOLuRv0OvSfgVAF7gqHIgTqw+dUvBDkyfYkcytmeDRZCCAmI9SO3iNP5nJkHs=

branches:
  only:
  - develop

script:
- npm install
- npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
